name: shubla
description: An entertaining game.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  # sensors: ^0.4.2+5
  # audioplayers: ^0.16.1

# dev_dependencies:
#   flutter_launcher_icons: "^0.8.0"
# flutter_test:
#   sdk: flutter

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/tick-tock.wav

  fonts:
    - family: Georgian
      fonts:
        - asset: assets/fonts/font.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
